# Generated by Django 2.2.3 on 2019-07-31 12:21

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license_number', models.CharField(blank=True, max_length=10, null=True)),
                ('categories_of_vehicles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('PESEL', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ch', 'Checked'), ('A', 'Available'), ('InR', 'In_Repair'), ('R', 'Rental'), ('F', 'In_the_future'), ('Un', 'Unavailable')], max_length=3)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=40)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_styles', models.CharField(choices=[('Se', 'Sedan'), ('V', 'Van'), ('C', 'Coupe'), ('H', 'Hatchback'), ('M', 'Minivan'), ('S', 'SUV')], max_length=2)),
                ('way_of_purchase', models.CharField(choices=[('L', 'Leasing'), ('FM', 'For_Money')], max_length=2)),
                ('fuel_types', multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Diesel'), ('P', 'Petrol'), ('E', 'Electric'), ('G', 'Gasoline'), ('H', 'Hybrid')], max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=40)),
                ('VIN', models.CharField(max_length=17)),
                ('transmission', models.CharField(choices=[('AM', 'Automanual'), ('A', 'Automatic'), ('M', 'Manual')], max_length=2)),
                ('year_of_manufacture', models.IntegerField()),
                ('next_review_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent', models.DateField()),
                ('end_rent', models.DateField()),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_day', models.DecimalField(decimal_places=0, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_rent', to='rent.Car')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_status', models.BooleanField(default=True)),
                ('insurance_company', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('type_of_insurance', multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Autocasco'), ('OC', 'OC'), ('NWW', 'NWW')], max_length=10)),
                ('worth_of_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance_number', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_insurance', to='rent.Car')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
